version: '3'

volumes:
  mongo_data:
  elastic_data:

services:
  mongo:
    image: tutum/mongodb:2.6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - AUTH=no

  elasticsearch:
    image: elasticsearch:1.3
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
